LDFLAGS := -lpthread
CFLAGS_INC := 
CFLAGS := -g -Wall $(CFLAGS_INC)

SRCS := $(wildcard *.c)
PRGS := $(patsubst %.c,%,$(SRCS))
BINS := $(patsubst %,%,$(PRGS))
OBJS := $(patsubst %,%.o,$(PRGS))

all : $(BINS)

.SECONDEXPANSION:
OBJ = $(patsubst %,%.o,$@)
BIN = $@

%$(BIN) : $(OBJS)
	$(CC) $(OBJ)  $(LDFLAGS) -o $(BIN)

clean:
	$(RM) $(BINS) $(OBJS)
