CC = gcc
libs = -lpthread
CFLAGS = -g

all: counter mutex_attr

counter_objs = counter.o

counter : $(counter_objs)
	$(CC) -o counter $(counter_objs) $(libs)

counter.o : counter.c
	$(CC) -c counter.c

mutex_attr_objs = mutex_attr.o

mutex_attr : $(mutex_attr_objs)
	$(CC) -o mutex_attr $(mutex_attr_objs) $(libs)

mutex_attr.o : mutex_attr.c
	$(CC) -c mutex_attr.c

clean :
	rm *.o counter mutex_attr
